development:
  adapter: mysql2
  database: mybi_development
  host: localhost
  username: root
  password: 
test:
    adapter: mysql2
    database: mybi_test
    host: localhost
    username: root
    password:
production:
    adapter: mysql2
    database: mybi
    host: localhost
    username: root
    password:
