development:
  adapter: mysql2
  database: yobi_development
  host: localhost
  username: root
  password: 
test:
    adapter: mysql2
    database: yobi_test
    host: localhost
    username: root
    password:
production:
    adapter: mysql2
    database: yobi
    host: localhost
    username: root
    password:
