site:
  url: www.51yobi.com
  name: 友比财务用品网上商城！
  home_title: 财务软件，财务配套，装订机，凭证，账册
  keywords: 财务软件，财务配套，装订机，凭证，账册
  description: 财务软件，财务配套，装订机，凭证，账册，我们更专业！
slides:
  slide1:
    image: /images/slides/slide-1.jpg
    url: http://www.51yobi.com
    title: 欢迎光临友比科技！
  slide2:
    image: /images/slides/slide-2.jpg
    url: http://www.51yobi.com
    title: 欢迎光临友比科技！
  slide3:
    image: /images/slides/slide-3.jpg
    url: http://www.51yobi.com
    title: 欢迎光临友比科技！
  slide4:
    image: /images/slides/slide-4.jpg
    url: http://www.51yobi.com
    title: 欢迎光临友比科技！
  slide5:
    image: /images/slides/slide-5.jpg
    url: http://www.51yobi.com
    title: 欢迎光临友比科技！

