site:
  url: www.51yobi.com
  name: 友比财务商城
  home_title: 国内专业财务配套用品网上商城
  keywords: 财务软件,财务配套,装订机,凭证,账册
  description: 友比财务商城-国内专业财务配套用品网上商城，为您提供：财务软件、财务表单（会计套打账册、业务表单）、装订系列（装订机、胶装机）、打印软件(套打软件、万能票据)等，满足财务电算化日常办公所需，实现企业规范、专业的信息化管理。
slides:
  slide1:
    image: /images/slides/slide-1.jpg
    title: 友比财务商城-国内专业的财务配套用品网上商城
  slide2:
    image: /images/slides/slide-2.jpg
    title: 友比财务商城-国内专业的财务配套用品网上商城
  slide3:
    image: /images/slides/slide-3.jpg
    title: 友比财务商城-国内专业的财务配套用品网上商城
